language: objective-c
osx_image: xcode8.2
script:
  - xcodebuild -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.2' build test GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f6539164e08e56cd75f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
